.Dd April 12, 2026
.Dt HEXII 1
.Os
.Sh NAME
.Nm hexii
.Nd a compact binary representation (mixing Hex and ASCII)
.Sh SYNOPSIS
.Nm hexii
.Op Fl aAeEhHqsSvxX
.Op Fl c Ar number
.Ar file
.Nm hexii
.Op Fl V
.Sh DESCRIPTION
The
.Nm
utility dumps file in HexII format.
HexII is a mixture of ASCII and Hex because ASCII dump is usually useless, unless there is an ASCII string,
in which case the HEX part is useless.
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl a
Enable ANSI color output (default).
.It Fl A
Disable ANSI color output.
.It Fl c Ar number
Format the output to
.Ar number
columns wide.
.It Fl e
Enable C escape-character output.
.It Fl E
Disable C escape-character output (default).
.It Fl h
Enable hex display mode for printable characters.
.It Fl H
Disable hex display mode (default).
.It Fl q
Quiet mode (disable verbose output).
.It Fl s
Squash blank lines (default).
.It Fl S
Do not squash blank lines.
.It Fl v
Enable verbose output.
.It Fl V
Print version information.
.It Fl x
Use lowercase hex digits.
.It Fl X
Use uppercase hex digits (default).
.El
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh SEE ALSO
.Xr hexdump 1 ,
.Xr od 1 ,
.Xr xxd 1
